replicaCount: 1

image:
  repository: classiq04/helm-nginx
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

containerPort: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

configMap:
  enabled: false
  data: {}

secret:
  enabled: false
  data: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

